### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by PrajaktaSathe** [PrajaktaSathe/Java#11]
These are the changes needed in the main readme file - 
- [ ] Contributors section at the bottom 
- [ ] List of programs in the repository

If anyone can contribute, do let me know.

**Comment by benardcharumbira** [comment]
@PrajaktaSathe  please assign this to me

**Comment by PrajaktaSathe** [comment]
> @PrajaktaSathe please assign this to me

Sure!
